// src/pages/Contact.vue
<template>
  <div class="flex flex-col min-h-screen overflow-hidden">

    <!-- Site header -->
    <Header />

    <!-- Page content -->
    <main class="flex-grow">

      <!-- Page illustration -->
      <div class="relative max-w-6xl mx-auto h-0 pointer-events-none -z-1" aria-hidden="true">
        <PageIllustration />
      </div>

      <section class="relative">
        <div class="max-w-6xl mx-auto px-4 sm:px-6 relative">
          <div class="pt-32 pb-12 md:pt-40 md:pb-20">

            <!-- Page header -->
            <div class="max-w-3xl mx-auto text-center pb-12 md:pb-16">
              <h1 class="h1 font-red-hat-display mb-4">A votre service !</h1>
              <p class="text-xl text-gray-600 dark:text-gray-400">Commençons votre projet en quelques secondes...</p>
            </div>

            <!-- Contact form -->
            <form class="max-w-xl mx-auto">
              <div class="flex flex-wrap -mx-3 mb-5">
                <div class="w-full md:w-1/2 px-3 mb-4 md:mb-0">
                  <label class="block text-gray-800 dark:text-gray-300 text-sm font-medium mb-1" for="first-name">Prénom <span class="text-red-600">*</span></label>
                  <input id="first-name" type="text" class="form-input w-full" placeholder="Mon prénom" required />
                </div>
                <div class="w-full md:w-1/2 px-3">
                  <label class="block text-gray-800 dark:text-gray-300 text-sm font-medium mb-1" for="last-name">Nom <span class="text-red-600">*</span></label>
                  <input id="last-name" type="text" class="form-input w-full" placeholder="Mon nom" required />
                </div>
              </div>
              <div class="flex flex-wrap -mx-3 mb-5">
                <div class="w-full px-3">
                  <label class="block text-gray-800 dark:text-gray-300 text-sm font-medium mb-1" for="company">Société  <span class="text-red-600">*</span></label>
                  <input id="company" type="text" class="form-input w-full" placeholder="Le nom de mon entreprise 🏛️" required />
                </div>
              </div>
              <div class="flex flex-wrap -mx-3 mb-5">
                <div class="w-full px-3">
                  <label class="block text-gray-800 dark:text-gray-300 text-sm font-medium mb-1" for="phone">Email <span class="text-red-600">*</span></label>
                  <input id="phone" type="tel" class="form-input w-full" placeholder="Mon adresse email" required />
                </div>
              </div>
              <div class="flex flex-wrap -mx-3 mb-5">
                <div class="w-full px-3">
                  <label class="block text-gray-800 dark:text-gray-300 text-sm font-medium mb-1" for="country">Thème <span class="text-red-600">*</span></label>
                  <select id="country" class="form-select w-full" required>
                    <option>Conseil</option>
                    <option>Product Design</option>
                    <option>Autre</option>
                  </select>
                </div>
              </div>
              <div class="flex flex-wrap -mx-3 mb-5">
                <div class="w-full px-3">
                  <div class="flex justify-between items-center mb-1">
                    <label class="block text-gray-800 dark:text-gray-300 text-sm font-medium" for="message">Details</label>
                    <span class="text-sm text-gray-500">Optional</span>
                  </div>
                  <textarea id="message" rows="4" class="form-textarea w-full" placeholder="Quelle est ma demande ? 📤"></textarea>
                </div>
              </div>
              <div class="flex flex-wrap -mx-3 mb-5">
                <div class="w-full px-3">
                  <div class="block text-gray-800 dark:text-gray-300 text-sm font-medium mb-3">Dites moi en plus sur votre rôle</div>
                  <label class="flex items-center mb-2">
                    <input type="radio" class="form-radio" name="role" />
                    <span class="text-sm text-gray-600 dark:text-gray-400 ml-3">Founder</span>
                  </label>
                  <label class="flex items-center mb-2">
                    <input type="radio" class="form-radio" name="role" />
                    <span class="text-sm text-gray-600 dark:text-gray-400 ml-3">Developer</span>
                  </label>
                  <label class="flex items-center mb-2">
                    <input type="radio" class="form-radio" name="role" />
                    <span class="text-sm text-gray-600 dark:text-gray-400 ml-3">Design / Marketing</span>
                  </label>
                  <label class="flex items-center mb-2">
                    <input type="radio" class="form-radio" name="role" />
                    <span class="text-sm text-gray-600 dark:text-gray-400 ml-3">Autre</span>
                  </label>
                </div>
              </div>
              <div class="flex flex-wrap -mx-3 mt-6">
                <div class="w-full px-3">
                  <button class="btn text-white bg-teal-500 hover:bg-teal-400 w-full flex items-center">
                    <span>Envoyer mon message</span>
                    <svg class="w-3 h-3 flex-shrink-0 mt-px ml-2" viewBox="0 0 12 12" xmlns="http://www.w3.org/2000/svg">
                      <path class="fill-current" d="M6.602 11l-.875-.864L9.33 6.534H0v-1.25h9.33L5.727 1.693l.875-.875 5.091 5.091z" />
                    </svg>
                  </button>
                </div>
              </div>
            </form>

          </div>
        </div>
      </section>

    </main>

    <!-- Site footer -->
    <Footer />

  </div>
</template>

<script>
import Header from './../partials/Header.vue'
import PageIllustration from './../partials/PageIllustration.vue'
import Footer from './../partials/Footer.vue'

export default {
  name: 'Contact',
  components: {
    Header,
    PageIllustration,
    Footer,
  },
}
</script>

// src/pages/Contact.jsx
import React from 'react';

import Header from '../partials/Header';
import PageIllustration from '../partials/PageIllustration';
import Footer from '../partials/Footer';

function Contact() {
  return (
    <div className="flex flex-col min-h-screen overflow-hidden">

      {/*  Site header */}
      <Header />

      {/*  Page content */}
      <main className="grow">

        {/*  Page illustration */}
        <div className="relative max-w-6xl mx-auto h-0 pointer-events-none" aria-hidden="true">
          <PageIllustration />
        </div>

        <section className="relative">
          <div className="max-w-6xl mx-auto px-4 sm:px-6 relative">
            <div className="pt-32 pb-12 md:pt-40 md:pb-20">

              {/* Page header */}
              <div className="max-w-3xl mx-auto text-center pb-12 md:pb-16">
                <h1 className="h1 mb-4" data-aos="fade-up">How can we help you?</h1>
                <p className="text-xl text-gray-400" data-aos="fade-up" data-aos-delay="200">We have custom plans to power your business. Tell us your needs, and we’ll contact you shortly.</p>
              </div>

              {/* Contact form */}
              <form className="max-w-xl mx-auto">
                <div className="flex flex-wrap -mx-3 mb-4">
                  <div className="w-full md:w-1/2 px-3 mb-4 md:mb-0">
                    <label className="block text-gray-300 text-sm font-medium mb-1" htmlFor="first-name">Prénom</label>
                    <input id="first-name" type="text" className="form-input w-full text-gray-300 border-red-500 focus:border-red-500" placeholder="Elon" required />
                    
                  </div>
                  <div className="w-full md:w-1/2 px-3">
                    <label className="block text-gray-300 text-sm font-medium mb-1" htmlFor="last-name">Nom</label>
                    <input id="last-name" type="text" className="form-input w-full text-gray-300" placeholder="Musk" required />
                  </div>
                </div>
                <div className="flex flex-wrap -mx-3 mb-4">
                  <div className="w-full px-3">
                    <label className="block text-gray-300 text-sm font-medium mb-1" htmlFor="email">Email</label>
                    <input id="email" type="email" className="form-input w-full text-gray-300" placeholder="elon.musk@spacex.com" required />
                  </div>
                </div>

                <div className="flex flex-wrap -mx-3 mb-4">
                  <div className="w-full px-3">
                    <label className="block text-gray-300 text-sm font-medium mb-1" htmlFor="message">Message</label>
                    <textarea id="message" rows="4" className="form-textarea w-full text-gray-300" placeholder="Hello ! Je suis Elon. Je cherche un Product Manager pour m'aider dans la création et le développement de mon produit." required ></textarea>
                  </div>
                </div>
                <div className="flex flex-wrap -mx-3 mb-4">
                  <div className="w-full px-3">
                    <label className="flex items-center">
                      <input type="checkbox" className="form-checkbox" />
                      <span className="text-gray-400 ml-2">J'accepte les conditions de confidentialités</span>
                    </label>
                  </div>
                </div>
                <div className="flex flex-wrap -mx-3 mt-6">
                  <div className="w-full px-3">
                    <button className="btn text-white bg-purple-600 hover:bg-purple-700 w-full">Envoyer</button>
                  </div>
                </div>
              </form>

            </div>
          </div>
        </section>

      </main>

      {/*  Site footer */}
      <Footer />

    </div>
  );
}

export default Contact;
